import streamlit as st
import pandas as pd
import joblib
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from fpdf import FPDF  # Ensure 'fpdf' is in requirements.txt

# --- PDF GENERATION HELPER ---
def create_pdf(df_to_print, user_details):
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="KCET 2026 College Prediction Report", ln=True, align='C')
    
    # User Details
    pdf.set_font("Arial", size=10)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Student Rank: {user_details['rank']} | Category: {user_details['cat']} | Target Branch: {user_details['branch']}", ln=True)
    pdf.ln(5)

    # Table Header
    pdf.set_fill_color(40, 167, 69) # GitHub Green
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(110, 10, " College Name", 1, 0, 'L', True)
    pdf.cell(45, 10, " Safety Range", 1, 0, 'L', True)
    pdf.cell(35, 10, " Status", 1, 1, 'L', True)

    # Table Body
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=9)
    for _, row in df_to_print.iterrows():
        # Shorten name if too long for PDF cell
        c_name = (row['College'][:60] + '..') if len(row['College']) > 60 else row['College']
        pdf.cell(110, 10, f" {c_name}", 1)
        pdf.cell(45, 10, f" {row['Safety Range']}", 1)
        pdf.cell(35, 10, f" {row['Status']}", 1)
        pdf.ln()
        
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(200, 10, txt="Generated by KCET AI Predictor. Values are estimates based on historical trends.", ln=True, align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# ... (Keep your existing Assets Loading and Sidebar Logic here) ...

# 5. Main UI Display
st.title("🎓 KCET 2026 College Predictor")

# Display Single Branch Results
if st.session_state.results_df is not None:
    if isinstance(st.session_state.results_df, str):
        st.error("No matches found for this branch.")
    else:
        st.subheader(f"📍 Recommended Colleges for {u_cour}")
        st.dataframe(st.session_state.results_df, use_container_width=True, hide_index=True)
        
        # --- NEW: PDF DOWNLOAD BUTTON ---
        user_info = {'rank': u_rank, 'cat': u_cat, 'branch': u_cour}
        try:
            pdf_bytes = create_pdf(st.session_state.results_df, user_info)
            st.download_button(
                label="📥 Download Recommendation Report (PDF)",
                data=pdf_bytes,
                file_name=f"KCET_2026_Report_{u_rank}.pdf",
                mime="application/pdf"
            )
        except Exception as e:
            st.error("Could not generate PDF. Check if all data is loaded.")

        # FEATURE 2: College Comparison Tool
        st.markdown("---")
        st.subheader("⚖️ Compare College Trends")
        st.write("Select up to 2 colleges to see their 2026 forecast trajectories.")
        
        selected_colls = st.multiselect("Select colleges to compare:", 
                                       st.session_state.results_df['College'].tolist(), 
                                       max_selections=2)
        
        if selected_colls:
            fig = go.Figure()
            colors = ['#007bff', '#e83e8c']
            forecast_notes = []
            
            for i, c_name in enumerate(selected_colls):
                h = df[(df['CollegeName'] == c_name) & (df['CourseName'] == u_cour) & 
                       (df['Base_Category'] == u_cat) & (df['Region'] == u_reg)].sort_values('Year')
                
                if not h.empty:
                    # History
                    fig.add_trace(go.Scatter(x=h['Year'], y=h['Cutoff_Rank'], name=f"{c_name} (History)",
                                             mode='lines+markers', line=dict(color=colors[i], width=2)))
                    
                    # Forecast
                    p_val = st.session_state.results_df[st.session_state.results_df['College'] == c_name]["Avg Cutoff"].values[0]
                    fig.add_trace(go.Scatter(x=[2025, 2026], y=[h['Cutoff_Rank'].iloc[-1], p_val],
                                             mode='lines+markers+text',
                                             name=f"{c_name} (2026 Forecast)", 
                                             text=["", f"<b>{int(p_val)}</b>"],
                                             textposition="top center",
                                             line=dict(color=colors[i], width=4, dash='dash')))
                    
                    forecast_notes.append(f"AI predicts **{c_name}** 2026 cutoff around: **{int(p_val)}**")
                else:
                    st.warning(f"Not enough historical data to generate a forecast for {c_name}.")

            fig.update_layout(title="Cutoff Comparison & 2026 Forecast", 
                              xaxis=dict(tickmode='linear', dtick=1),
                              yaxis_title="Rank", 
                              hovermode="x unified")
            st.plotly_chart(fig, use_container_width=True)
            
            for note in forecast_notes:
                st.success(note)
        else:
            st.info("Pick a college from the list above to view the trend graph.")

# Display Top 5 Best Fit
if st.session_state.top_5_df is not None:
    if isinstance(st.session_state.top_5_df, str):
        st.error("Could not find suitable matches across branches.")
    else:
        st.success("🎯 Here are the Top 5 best colleges you can get based on your rank!")
        st.table(st.session_state.top_5_df[["College", "Branch", "Est. Cutoff"]])
        
        # Optional: Add a PDF button for Top 5 as well
        # (You can repeat the PDF logic here if you want a separate report for Top 5)

# FEATURE 3: User Feedback Loop
st.markdown("---")
st.write("### 💬 Was this prediction helpful?")
col_f1, col_f2 = st.columns([1, 5])
with col_f1:
    if st.button("👍 Yes"): st.toast("Thanks for your feedback!")
with col_f2:
    if st.button("👎 No"): st.toast("We'll work on improving the AI.")

st.caption("Note: Predictions are based on historical data trends and AI modeling. Actual 2026 cutoffs may vary.")
