import streamlit as st
import pandas as pd
import joblib
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from fpdf import FPDF  # --- NEW IMPORT ---
import base64

# 1. Setup & Assets
st.set_page_config(page_title="KCET 2026 Pro Predictor", page_icon="🎓", layout="centered")

st.markdown("""
    <style>
    .main { background-color: #f8f9fa; }
    div.stButton > button:first-child {
        background-color: #28a745;
        color: white;
        border-radius: 6px;
        font-weight: bold;
        height: 3em;
        width: 100%;
    }
    .difficulty-tag { font-weight: bold; padding: 2px 8px; border-radius: 4px; }
    /* Style for the PDF Download Button */
    .stDownloadButton > button {
        background-color: #007bff !important;
        color: white !important;
        width: 100%;
    }
    </style>
    """, unsafe_allow_html=True)

# --- NEW: PDF GENERATION FUNCTION ---
def create_pdf(df_to_print, user_details):
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="KCET 2026 College Prediction Report", ln=True, align='C')
    
    # User Profile Section
    pdf.set_font("Arial", size=10)
    pdf.ln(10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(200, 10, txt=f" STUDENT PROFILE", ln=True, fill=True)
    pdf.cell(200, 8, txt=f" Rank: {user_details['rank']} | Category: {user_details['cat']} | Quota: {user_details['quota']}", ln=True)
    pdf.cell(200, 8, txt=f" Region: {user_details['region']} | Target Branch: {user_details['branch']}", ln=True)
    pdf.ln(5)

    # Table Header
    pdf.set_fill_color(40, 167, 69) # GitHub Green
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(110, 10, " College Name", 1, 0, 'L', True)
    pdf.cell(45, 10, " Safety Range", 1, 0, 'L', True)
    pdf.cell(35, 10, " Status", 1, 1, 'L', True)

    # Table Body
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=9)
    for _, row in df_to_print.iterrows():
        # Handle long college names
        name = (row['College'][:60] + '..') if len(row['College']) > 60 else row['College']
        pdf.cell(110, 10, f" {name}", 1)
        pdf.cell(45, 10, f" {row['Safety Range']}", 1)
        pdf.cell(35, 10, f" {row['Status']}", 1)
        pdf.ln()
        
    pdf.ln(15)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, txt="Disclaimer: These predictions are generated by an AI model based on historical trends (2023-2025). Actual cutoffs for 2026 may vary based on seat matrix and student preferences.", align='C')
    
    # Signature / Credit
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 9)
    pdf.cell(0, 10, txt="Developed by Gemini & KCET AI Predictor Team", ln=True, align='C')
    
    return pdf.output(dest='S').encode('latin-1')

@st.cache_resource
def load_assets():
    model = joblib.load('kcet_model_slim.pkl')
    le_coll = joblib.load('encoder_college.pkl')
    le_cour = joblib.load('encoder_course.pkl')
    le_cat = joblib.load('encoder_base_cat.pkl')
    le_quot = joblib.load('encoder_quota.pkl')
    le_reg = joblib.load('encoder_region.pkl')
    df = pd.read_csv('kcet_ai_ready.csv')
    return model, le_coll, le_cour, le_cat, le_quot, le_reg, df

model, le_coll, le_cour, le_cat, le_quot, le_reg, df = load_assets()

# Initialize Session States
if 'results_df' not in st.session_state: st.session_state.results_df = None
if 'top_5_df' not in st.session_state: st.session_state.top_5_df = None

# Helper: Calculate Difficulty Score
def get_difficulty(college, course, cat, reg):
    hist = df[(df['CollegeName'] == college) & (df['CourseName'] == course) & 
              (df['Base_Category'] == cat) & (df['Region'] == reg)].sort_values('Year')
    if len(hist) < 2: return "⚪ Stable"
    
    first = hist['Cutoff_Rank'].iloc[0]
    last = hist['Cutoff_Rank'].iloc[-1]
    change = ((last - first) / first) * 100
    
    if change < -5: return "🔴 Getting Harder"
    elif change > 5: return "🟢 Getting Easier"
    else: return "🔵 Stable"

# 2. Sidebar
with st.sidebar:
    st.header("📋 Student Profile")
    u_rank = st.number_input("Your Rank", min_value=1, value=25000)
    u_reg = st.selectbox("Region", le_reg.classes_)
    u_cat = st.selectbox("Category", le_cat.classes_)
    u_quot = st.selectbox("Quota", le_quot.classes_)
    u_cour = st.selectbox("Target Branch", sorted(le_cour.classes_))
    
    predict_btn = st.button("🚀 Predict for 2026")
    best_fit_btn = st.button("📍 Find My Best Fit (All Branches)")

# 3. Logic: Single Branch Prediction
if predict_btn:
    st.session_state.top_5_df = None
    with st.spinner('Analyzing trends...'):
        targets = df[df['CourseName'] == u_cour].drop_duplicates('CollegeName')
        preds = []
        for _, row in targets.iterrows():
            try:
                feat = np.array([[le_coll.transform([row['CollegeName']])[0], 
                                 le_cour.transform([u_cour])[0], le_cat.transform([u_cat])[0],
                                 le_quot.transform([u_quot])[0], le_reg.transform([u_reg])[0], 2026]])
                p_rank = np.expm1(model.predict(feat))[0]
                
                if u_rank <= (p_rank * 1.4):
                    status = "✅ High Chance" if u_rank <= p_rank else "🟡 Borderline"
                    diff = get_difficulty(row['CollegeName'], u_cour, u_cat, u_reg)
                    range_str = f"{int(p_rank*0.9):,} - {int(p_rank*1.1):,}"
                    
                    preds.append({
                        "College": row['CollegeName'], 
                        "Safety Range": range_str,
                        "Avg Cutoff": int(p_rank),
                        "Status": status,
                        "Trend": diff
                    })
            except: continue
        st.session_state.results_df = pd.DataFrame(preds).sort_values("Avg Cutoff") if preds else "No Matches"

# 4. Logic: Top 5 Best Fit
if best_fit_btn:
    st.session_state.results_df = None
    with st.spinner('Scanning all branches...'):
        all_colleges = df.drop_duplicates(['CollegeName', 'CourseName']).sample(150)
        fits = []
        for _, row in all_colleges.iterrows():
            try:
                feat = np.array([[le_coll.transform([row['CollegeName']])[0], 
                                 le_cour.transform([row['CourseName']])[0], le_cat.transform([u_cat])[0],
                                 le_quot.transform([u_quot])[0], le_reg.transform([u_reg])[0], 2026]])
                p_rank = np.expm1(model.predict(feat))[0]
                if p_rank >= u_rank:
                    fits.append({
                        "College": row['CollegeName'],
                        "Branch": row['CourseName'],
                        "Est. Cutoff": int(p_rank),
                        "Match Score": int(p_rank - u_rank)
                    })
            except: continue
        st.session_state.top_5_df = pd.DataFrame(fits).sort_values("Match Score").head(5) if fits else "No Matches"

# 5. Main UI Display
st.title("🎓 KCET 2026 College Predictor")

if st.session_state.results_df is not None:
    if isinstance(st.session_state.results_df, str):
        st.error("No matches found for this branch.")
    else:
        st.subheader(f"📍 Recommended Colleges for {u_cour}")
        st.dataframe(st.session_state.results_df, use_container_width=True, hide_index=True)
        
        # --- NEW: PDF DOWNLOAD SECTION ---
        st.markdown("<br>", unsafe_allow_html=True)
        user_info = {'rank': u_rank, 'cat': u_cat, 'quota': u_quot, 'region': u_reg, 'branch': u_cour}
        
        try:
            pdf_bytes = create_pdf(st.session_state.results_df, user_info)
            st.download_button(
                label="📥 Download Recommendation Report (PDF)",
                data=pdf_bytes,
                file_name=f"KCET_2026_Report_{u_rank}.pdf",
                mime="application/pdf"
            )
        except Exception as e:
            st.error(f"Error generating PDF: {e}")

        # FEATURE 2: Comparison Tool
        st.markdown("---")
        st.subheader("⚖️ Compare College Trends")
        selected_colls = st.multiselect("Select colleges to compare:", 
                                       st.session_state.results_df['College'].tolist(), 
                                       max_selections=2)
        
        if selected_colls:
            fig = go.Figure()
            colors = ['#007bff', '#e83e8c']
            forecast_notes = []
            
            for i, c_name in enumerate(selected_colls):
                h = df[(df['CollegeName'] == c_name) & (df['CourseName'] == u_cour) & 
                       (df['Base_Category'] == u_cat) & (df['Region'] == u_reg)].sort_values('Year')
                
                if not h.empty:
                    fig.add_trace(go.Scatter(x=h['Year'], y=h['Cutoff_Rank'], name=f"{c_name} (History)",
                                             mode='lines+markers', line=dict(color=colors[i], width=2)))
                    p_val = st.session_state.results_df[st.session_state.results_df['College'] == c_name]["Avg Cutoff"].values[0]
                    fig.add_trace(go.Scatter(x=[2025, 2026], y=[h['Cutoff_Rank'].iloc[-1], p_val],
                                             mode='lines+markers+text',
                                             name=f"{c_name} (Forecast)", 
                                             text=["", f"<b>{int(p_val)}</b>"],
                                             textposition="top center",
                                             line=dict(color=colors[i], width=4, dash='dash')))
                    forecast_notes.append(f"AI predicts **{c_name}** 2026 cutoff around: **{int(p_val)}**")

            fig.update_layout(xaxis=dict(tickmode='linear', dtick=1), yaxis_title="Rank", hovermode="x unified")
            st.plotly_chart(fig, use_container_width=True)
            for note in forecast_notes: st.success(note)

# Display Top 5 Best Fit
if st.session_state.top_5_df is not None:
    if isinstance(st.session_state.top_5_df, str):
        st.error("No suitable matches found.")
    else:
        st.success("🎯 Top 5 Best Fits Across All Branches")
        st.table(st.session_state.top_5_df[["College", "Branch", "Est. Cutoff"]])

# FEATURE 3: User Feedback Loop
st.markdown("---")
st.write("### 💬 Was this prediction helpful?")
col_f1, col_f2 = st.columns([1, 5])
if col_f1.button("👍 Yes"): st.toast("Thanks for your feedback!")
if col_f2.button("👎 No"): st.toast("We'll work on improving!")

st.caption("Note: Actual 2026 cutoffs may vary.")
